#!/bin/bash
cd ..
unset GIT_DIR
while read oldrev newrev refname
do
  branch=$(git rev-parse --symbolic --abbrev-ref $refname)
  if [ "master" = "$branch" ]; then
    echo "slnn: checkout master"
    git checkout -q master || git checkout -q -b master
    echo "slnn: delete serverside branch"
    git branch -q -D serverside
    git reset HEAD --hard
    
    echo "slnn: installing node modules"
    npm install --production
    test1
    test2
    echo "slnn: restarting service test"
    service test stop
    echo 'test'
    service test start
    
  elif [ "clientside" = "$branch" ]; then
    echo "slnn: checkout serverside branch"
    git checkout -q serverside || git checkout -q -b serverside
    echo "slnn: commit serverside changes"
    git add .
    git commit -q -m "serverside changes"
  fi
done